# Site settings
title: Robb Lewis
description: "Robb Lewis developer in Portsmouth, UK. Blogs about technology, development and the web."
baseurl: ""
url: "http://robblewis.me"

# Build settings
markdown: kramdown
