name: Robb Lewis
description: "Robb Lewis developer in Portsmouth, UK. Blogs about technology, development and the web."
markdown: redcarpet
pygments: true
permalink: /:title
paginate: 10
paginate_path: "blog/page/:num"
relative_permalinks: true